version: "3.8"

services:
  app:
    build: .
    environment:
      OTRA_VARIABLE: "Variable de Ejemplo"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm start

  db:
    image: mongo
